version: '3'
services:
  nobox-core:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map the container's port to the host machine (adjust as needed)
    environment:
      - NODE_ENV=dev # Set the Node.js environment as needed
    deploy:
      resources:
        limits:
          memory: 8012M # Set the memory limit for the container
        reservations:
          cpus: "1.5" # Set the CPU limit for the container (1.5 CPU shares)
